hgraph-io/hgraph-docs

docusaurus.config.ts
fixes build issues (incorrect config)
=> fix for google analytics

docs/faq/_category_.json, docs/faq/faq-api.md, docs/faq/faq-general.md, docs/overview/_category_.json, docs/overview/about.md, docs/overview/contact.md, docs/overview/services.md, docs/welcome.md
we have all of our starter content ready to go, this is a final review with some updates and fixes
=> initial content final review

README.md, docs/hgraph-sdk/examples.md
updated readme and examples section to add react native example
=> react native template

docs/hedera-stats/revenue.md
Added information regarding account 801 to match our new calculations
=> Update Hedera revenue methodology

docs/faq/faq-general.md, docs/overview/contact.md, docs/overview/pricing.md, src/css/custom.css
This PR adds the new pricing details page to our docs and updates the CSS file for table styling. It also updates sidebar positioning for the contact page. It also removes a question from the existing FAQ page.
=> Add pricing details page

docs/overview/pricing.md
The pricing page is updated to communicate that our account dashboard is coming soon and customers can easily get started while we get the work finished.
=> Temporary sign up notice

docs/faq/_category_.json, docs/faq/faq-api.md, docs/faq/faq-enterprise.md, docs/faq/faq-general.md, docs/support.md
Updated FAQs for APIs and general, added an enterprise FAQ. updated the support page.
=> Adding new FAQs and updating support

docs/faq/faq-api.md
added 10 second timeout to the api faq page
=> add timeout to faq

docs/faq/faq-api.md, docs/faq/faq-enterprise.md, docs/faq/faq-general.md
Feedback from our call:
- move items from General to Hedera section
- Add area to General about hosting/infra
=> Add revisions to FAQ

docs/hedera-stats/account-growth.md, docs/hedera-stats/active-accounts.md, docs/hedera-stats/active-contracts.md, docs/hedera-stats/developer-accounts.md, docs/hedera-stats/hbar-price.md, docs/hedera-stats/introduction.md, docs/hedera-stats/retail-accounts.md, docs/hedera-stats/revenue.md, docs/hedera-stats/stablecoin-market-cap.md, docs/hedera-stats/time-to-consensus.md, docs/hedera-stats/top-50-contracts.md, docs/hedera-stats/top-50-fungible-tokens.md, docs/hedera-stats/top-50-non-fungible-tokens.md, docs/hedera-stats/total-value-locked.md, docs/hedera-stats/transaction-volume.md, docs/hedera-stats/transactions-per-second.md
this PR changes the navigation and content to publish P1/P2 metrics.
it also adds final checks against SQL queries.
=> publish p2 metrics docs

docs/faq/faq-api.md, docs/faq/faq-enterprise.md, docs/faq/faq-general.md, docs/graphql-api/common-queries.md, docs/hgraph-sdk/endpoints-authorization.md, docs/hgraph-sdk/examples.md, docs/hgraph-sdk/installation.md, docs/overview/about.md, docs/overview/contact.md, docs/overview/pricing.md, docs/overview/services.md, docs/welcome.md
=> fix various pages

docusaurus.config.ts
this PR updates the docusaurus config to enable Algoria indexing for Docusearch.
it also fixes some outdated navigation items.
=> adding docs search and fix nav

docs/hedera-stats/active-accounts.md, docs/hedera-stats/active-contracts.md, docs/hedera-stats/developer-accounts.md, docs/hedera-stats/introduction.md, docs/hedera-stats/retail-accounts.md, docs/hedera-stats/revenue.md, docs/hedera-stats/stablecoin-market-cap.md, docs/hedera-stats/time-to-consensus.md, docs/hedera-stats/total-value-locked.md, docs/hgraph-sdk/endpoints-authorization.md
this PR updates the introduction page with instructions on how to discover available Hedera network statistics.
it also adds a working GraphQL query example for each methodology as well as available date formats.
=> Update Hedera Stats Docs

docs/hedera-stats/active-accounts.md, docs/hedera-stats/active-contracts.md, docs/hedera-stats/developer-accounts.md, docs/hedera-stats/retail-accounts.md, docs/hedera-stats/revenue.md
this PR fixes a number of GraphQL query examples to more accurately reflect use cases and fix errors
=> Fix Hedera Stats Query examples

docs/graphql-assistant.md
this PR creates a new page of documentation for the Hgraph AI GraphQL Query Assistant.
try the assistant: https://hgraph.com/assistant
=> Hgraph AI Assistant page

docs/hedera-stats/time-to-consensus.md
this PR adds prometheus setup to the time to consensus page
=> update ttc page

docs/json-rpc/beta.md
this PR will update the endpoints for the beta JSON-RPC page
=> HG-628 - Update RPC endpoints

docs/hedera-stats/active-accounts.md, docs/hedera-stats/active-contracts.md, docs/hedera-stats/developer-accounts.md, docs/hedera-stats/hbar-price.md, docs/hedera-stats/retail-accounts.md, docs/hedera-stats/revenue.md, docs/hedera-stats/stablecoin-market-cap.md, docs/hedera-stats/time-to-consensus.md, docs/hedera-stats/total-value-locked.md, docs/hedera-stats/transactions-per-second.md
These now match the ones on the dashboard
=> Adding new query examples

docs/overview/dashboard.md
- embed a pricing & dashboard walkthrough video in the dashboard doc
- `npm run typecheck` *(fails: Cannot find module 'prism-react-renderer')*
=> Add dashboard walkthrough video

docs/hedera-stats/introduction.md, docs/overview/about.md
This applies some simple updates
=> Updates to Bento Box and Hedera Stats Intro

docs/hedera-stats/introduction.md, docs/hedera-stats/misc.md, docs/hedera-stats/nft-collection-sales-volume-total.md, docs/hedera-stats/nft-collection-sales-volume.md
this PR creates new .md files that document NFT collection sales volume statistics.
- `ecosystem_nft_collection_sales_volume`
- `ecosystem_nft_collection_sales_volume_total`
=> NFT Sales Volume Methodlogy
